@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "timerCounter",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_282648841 { 
   	label=timerCounter
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   timerCounter282648841[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)timerCounter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   minutes: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   seconds: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timeUpdateListener: TimeUpdateListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timer: Timer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># timerUpdate()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_71862 { 
   	label=Gra
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Gra71862[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Gra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   counter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   score: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timerCounterInstance: timerCounter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   topic_1: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   topic_2: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   topic_3: JLabel [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- getCurrentScore(label: JLabel): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseClicked(e: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseEntered(e: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseExited(e: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mousePressed(e: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseReleased(e: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTimeUpdate(formattedTime: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ randomNum(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ randomNum2(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Gra71862 -> timerCounter282648841[label="timerCounterInstance
[0..1]"];
timerCounter282648841 -> Gra71862[arrowhead=none];
timerCounter282648841 -> Gra71862[label="timeUpdateListener
[0..1]", arrowhead=none];
    
}
@enduml